

# Markov chain on unit circle




In [3]:
!pip install numpy

In [4]:
import numpy as np
from numpy import linalg as LA

In [5]:
A = np.matrix('0 0.5 0.5; 0.5 0 0.5; 0.5 0.5 0') 

In [10]:
A

matrix([[0. , 0.5, 0.5],
        [0.5, 0. , 0.5],
        [0.5, 0.5, 0. ]])

In [7]:
LA.eigvals(A)

array([-0.5,  1. , -0.5])

In [57]:
LA.eig(A)

(array([-0.5,  1. , -0.5]),
 matrix([[-0.81649658,  0.57735027,  0.0619941 ],
         [ 0.40824829,  0.57735027, -0.73606268],
         [ 0.40824829,  0.57735027,  0.67406859]]))

In [8]:
C = LA.eig(A)[1]
C

matrix([[-0.81649658,  0.57735027,  0.19219669],
        [ 0.40824829,  0.57735027, -0.7833358 ],
        [ 0.40824829,  0.57735027,  0.59113912]])

In [59]:
B = np.diag(LA.eigvals(A)) # diagonalized form of A

In [60]:
B

array([[-0.5,  0. ,  0. ],
       [ 0. ,  1. ,  0. ],
       [ 0. ,  0. , -0.5]])

In [11]:
N = 10


In [12]:
A**N

matrix([[0.33398438, 0.33300781, 0.33300781],
        [0.33300781, 0.33398438, 0.33300781],
        [0.33300781, 0.33300781, 0.33398438]])

In [13]:
B**N

NameError: name 'B' is not defined

In [64]:
LA.inv(C)

matrix([[-8.16496581e-01,  3.54404400e-01,  4.62092181e-01],
        [ 5.77350269e-01,  5.77350269e-01,  5.77350269e-01],
        [ 3.93659459e-17, -7.09153837e-01,  7.09153837e-01]])

In [66]:
C*(B**N)*LA.inv(C)

matrix([[0.33398437, 0.33300781, 0.33300781],
        [0.33300781, 0.33398437, 0.33300781],
        [0.33300781, 0.33300781, 0.33398437]])